name: Flutter Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  create-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install & set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'
          channel: 'stable'
      - name: Get package
        run: flutter pub get
      - name: Build runner
        run: dart run build_runner build
      - name: Run test
        run: flutter test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
